### ISSUE TITLE
Can't specify python version for testing of built dists

### ISSUE THREAD

**Issue by tepickering** [OpenAstronomy/build-python-dist#8]
I don't see any examples of how to specify a python version for running tests. In looking at the workflow itself, it looks like it's hard-coded to `3.x`. I have dependencies that still don't support 3.10 so need to stick with 3.9 for now. With my normal `tox` testing workflow, this isn't an issue. My workaround is to not use testing in the build workflow, but it would be nice to as an extra consistency check.

**Comment by astrofrog** [comment]
I agree we should support specifying the Python version!
